# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Cypress test from spec

on:
      
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- run: git pull
    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
          build: npm run build
          start: npm run cy:spec
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Running Cypress Test"
        commit_user_name: cjvillar
        commit_user_email: cjvillar@ucsc.edu
